name: build oses
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    paths:
      - oses/**
jobs:
  push:
    name: "Push"
    runs-on: ubuntu-latest
    strategy: 
      fail-fast: false
      matrix:
        oses: 
          - .
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.oses }}
          file: ./${{ matrix.oses }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/bartixxx32/fivem:${{ matrix.oses }}
